# Generated by Django 4.2.4 on 2023-09-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_red', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='main/imagenes/redesSociales')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='HistorialEducativo',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='HistorialEmpleo',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='Intereses',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('listavalores_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cvs.listavalores')),
            ],
            bases=('app_cvs.listavalores',),
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('fotoPerfil', models.ImageField(null=True, upload_to='main/imagenes/fotosPerfil')),
                ('presentacion', models.CharField(max_length=2500)),
                ('tipoPlantilla', models.CharField(max_length=50)),
                ('redesSociales', models.ManyToManyField(to='app_cvs.redessociales')),
                ('contacto', models.ManyToManyField(to='app_cvs.contacto')),
                ('historialEducativo', models.ManyToManyField(to='app_cvs.historialeducativo')),
                ('historialEmpleo', models.ManyToManyField(to='app_cvs.historialempleo')),
                ('intereses', models.ManyToManyField(to='app_cvs.intereses')),
                ('otros', models.ManyToManyField(to='app_cvs.otros')),
                ('perfilProfesional', models.ManyToManyField(to='app_cvs.perfilprofesional')),
                ('software', models.ManyToManyField(to='app_cvs.software')),
            ],
        ),
    ]
