# Generated by Django 4.2.4 on 2023-10-19 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250, null=True)),
                ('subtitulo', models.CharField(max_length=250, null=True)),
                ('fotoPerfil', models.ImageField(null=True, upload_to='main/imagenes/fotosPerfil')),
                ('contacto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('presentacion', models.CharField(max_length=2500, null=True)),
                ('perfilProfesional', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('intereses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('historialEmpleo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('historialEducativo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('otros', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('software', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), null=True, size=None)),
                ('tipoPlantilla', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_red', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='main/imagenes/redesSociales')),
            ],
        ),
    ]
