# Generated by Django 4.2.4 on 2023-10-19 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='contacto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='historialEducativo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='historialEmpleo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='intereses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='otros',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='perfilProfesional',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='software',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), null=True, size=None),
        ),
    ]
